Repository OWOX/owox-data-marts, pull requests merged in 2025-09, with the labels that each got.

#482 (linkedin): update LinkedIn Pages instructions and code
  packages/connectors/src/Sources/LinkedInPages/GETTING_STARTED.md
  packages/connectors/src/Sources/LinkedInPages/Source.js
  packages/connectors/src/Sources/LinkedInPages/res/linkedin_account.png
  packages/connectors/src/Sources/LinkedInPages/res/linkedin_backfill.png
  packages/connectors/src/Sources/LinkedInPages/res/linkedin_bq.png
  packages/connectors/src/Sources/LinkedInPages/res/linkedin_credentials.png
  packages/connectors/src/Sources/LinkedInPages/res/linkedin_dataset.png
  packages/connectors/src/Sources/LinkedInPages/res/linkedin_date.png
  packages/connectors/src/Sources/LinkedInPages/res/linkedin_fields.png
  packages/connectors/src/Sources/LinkedInPages/res/linkedin_import.png
  packages/connectors/src/Sources/LinkedInPages/res/linkedin_importsheets.png
  packages/connectors/src/Sources/LinkedInPages/res/linkedin_newdata.png
  packages/connectors/src/Sources/LinkedInPages/res/linkedin_pages_bq.png
  packages/connectors/src/Sources/LinkedInPages/res/linkedin_pasteurn.png
  packages/connectors/src/Sources/LinkedInPages/res/linkedin_reimport.png
  packages/connectors/src/Sources/LinkedInPages/res/linkedin_request.png
  packages/connectors/src/Sources/LinkedInPages/res/linkedin_runbackfill.png
  packages/connectors/src/Sources/LinkedInPages/res/linkedin_success.png
  packages/connectors/src/Sources/LinkedInPages/res/linkedin_token.png
Labels: documentation, connector

#480 fix(backend): report delete no longer fails due to cache FK
  apps/backend/src/data-marts/entities/report-data-cache.entity.ts
  apps/backend/src/migrations/1756904880000-add-cascade-to-report-data-cache-fk.ts
Labels: bug

#510 fix(backend): fix time based triggers on mysql db
  apps/backend/src/common/scheduler/services/fetchers/time-based-trigger-fetcher.service.ts
Labels: bug

#479 feat(docs): add environment variables documentation
  docs/getting-started/deployment-guide/environment-variables.md
Labels: documentation

#513 docs(facebook): fix step numbering
  packages/connectors/src/Sources/FacebookMarketing/CREDENTIALS.md
Labels: documentation

#511 refactor(idp-better-auth): refactor BetterAuth to DatabaseStore with SQLite/MySQL support
  .env.example
  apps/owox/src/commands/idp/add-user.ts
  packages/idp-better-auth/README.md
  packages/idp-better-auth/src/adapters/database.ts
  packages/idp-better-auth/src/auth/auth-config.ts
  packages/idp-better-auth/src/index.ts
  packages/idp-better-auth/src/providers/better-auth-provider.ts
  packages/idp-better-auth/src/services/database-service.ts
  packages/idp-better-auth/src/services/user-management-service.ts
  packages/idp-better-auth/src/store/DatabaseStore.ts
  packages/idp-better-auth/src/store/DatabaseStoreFactory.ts
  packages/idp-better-auth/src/store/MysqlDatabaseStore.ts
  packages/idp-better-auth/src/store/SqliteDatabaseStore.ts
  packages/idp-better-auth/src/templates/password-success.html
  packages/idp-better-auth/src/types/database-models.ts
Labels: enhancement

#497 feat(backend): make migration handling for multiple instances
  apps/backend/src/config/migrations.config.ts
Labels: enhancement

#548 fix(LinkedIn): Remove API version config and hardcode LinkedIn-Version header
  packages/connectors/src/Sources/LinkedInAds/Source.js
  packages/connectors/src/Sources/LinkedInPages/Source.js
Labels: connector

#550 docs(root): added changeset about mysql ssl connections
  .changeset/mysql-ssl-connection.md
Labels: documentation

#505 Facebook Getting Started Guide improvement
  packages/connectors/src/Sources/FacebookMarketing/GETTING_STARTED.md
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_currentday.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_daterange.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_endpoint.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_importgbq.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_incremental.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_inputsource.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_newdatamart.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_nodejs_storage.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_publish.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_reimportwindow.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_setupconnector.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_successrun.png
Labels: documentation
