Repository OWOX/owox-data-marts, pull requests merged in 2025-07, with the labels that each got.

#227 docs(owox): updated docs with linter rules
  apps/owox/CONTRIBUTING.md
  apps/owox/PUBLISHING.md
  apps/owox/README.md
Labels: documentation

#237 feat(owox): added json per-line logger
  apps/owox/src/commands/base.ts
  apps/owox/src/commands/serve.ts
Labels: enhancement

#253 feat(owox): update cross-platform zombie process cleanup
  apps/owox/package.json
  apps/owox/src/commands/serve.ts
  package-lock.json
Labels: enhancement

#269 docs(owox): add issue block to README.md
  apps/owox/README.md
Labels: documentation

#270 feat(root): updated husky hooks creation script
  tools/setup-husky.mjs
Labels: enhancement

#301 fix(backend): update static configurations
  apps/backend/src/config/express-static.config.ts
Labels: bug

#307 feat(docs): added gtm id from env
  .github/workflows/deploy-docs.yml
  apps/docs/.env.example
  apps/docs/astro.config.mjs
  apps/docs/scripts/env-config.js
  apps/docs/src/components/starlight/PageFrame.astro
Labels: enhancement

#344 docs: reorganize Facebook Ads API credential guide and improve TikTok Ads token exp handling
  packages/connectors/src/Sources/FacebookMarketing/CREDENTIALS.md
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_datahandling.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_description.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_entity.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_next.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_personal.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_personaldata.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_standard_access.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_ver.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_video.png
  packages/connectors/src/Sources/TikTokAds/CREDENTIALS.md
  packages/connectors/src/Sources/TikTokAds/Code.gs
Labels: documentation

#375 feat(docs): add changelog to the docs.owox.com
  .gitattributes
  .github/workflows/release-pr.yml
  .markdownlint-cli2.mjs
  apps/backend/CHANGELOG.md
  apps/docs/astro.config.mjs
  apps/docs/scripts/sync-docs.js
  apps/owox/CHANGELOG.md
  packages/connector-runner/CHANGELOG.md
  tools/fix-changelog-headings.mjs
Labels: documentation
