Repository OWOX/owox-data-marts, pull requests merged in 2025-06, with the labels that each got.

#67 On branch reddit_connector_v0.1
  packages/connectors/src/Integrations/RedditAds/.clasp.json
  packages/connectors/src/Integrations/RedditAds/.claspignore
  packages/connectors/src/Integrations/RedditAds/Code.gs
  packages/connectors/src/Integrations/RedditAds/Connector.js
  packages/connectors/src/Integrations/RedditAds/Helper.js
  packages/connectors/src/Integrations/RedditAds/Pipeline.js
  packages/connectors/src/Integrations/RedditAds/RedditAdsAPIReference/FieldsSchema.js
  packages/connectors/src/Integrations/RedditAds/RedditAdsAPIReference/ad-account-user.js
  packages/connectors/src/Integrations/RedditAds/RedditAdsAPIReference/ad-account.js
  packages/connectors/src/Integrations/RedditAds/RedditAdsAPIReference/ad-funding-instruments.js
  packages/connectors/src/Integrations/RedditAds/RedditAdsAPIReference/ad-group.js
  packages/connectors/src/Integrations/RedditAds/RedditAdsAPIReference/ad-lead-gen-form.js
  packages/connectors/src/Integrations/RedditAds/RedditAdsAPIReference/ad-reports.js
  packages/connectors/src/Integrations/RedditAds/RedditAdsAPIReference/ad-user-custom-audience.js
  packages/connectors/src/Integrations/RedditAds/RedditAdsAPIReference/ads.js
  packages/connectors/src/Integrations/RedditAds/RedditAdsAPIReference/campaigns.js
Labels: connector

#117 Move storages from Core to indevidul folder.
  packages/connectors/src/Configs/AppsScript/GoogleSheetsConfig.js
  packages/connectors/src/Integrations/BankOfCanada/.claspignore
  packages/connectors/src/Integrations/BingAds/.claspignore
  packages/connectors/src/Integrations/CriteoAds/.claspignore
  packages/connectors/src/Integrations/FacebookMarketing/.claspignore
  packages/connectors/src/Integrations/LinkedIn/.claspignore
  packages/connectors/src/Integrations/OpenExchangeRates/.claspignore
  packages/connectors/src/Integrations/RedditAds/.claspignore
  packages/connectors/src/Integrations/TikTokAds/.claspignore
  packages/connectors/src/Integrations/XAds/.claspignore
  packages/connectors/src/Storages/AwsAthena/AwsAthenaStorage.js
  packages/connectors/src/Storages/AwsAthena/manifest.json
  packages/connectors/src/Storages/GoogleBigQuery/GoogleBigQueryStorage.js
  packages/connectors/src/Storages/GoogleBigQuery/manifest.json
  packages/connectors/src/Storages/GoogleSheets/GoogleSheetsStorage.js
  packages/connectors/src/Storages/GoogleSheets/manifest.json
Labels: connector

#126 Implement pre-commit hooks with linting and formatting
  .gitignore
  apps/backend/.prettierignore
  apps/backend/.prettierrc
  apps/backend/eslint.config.cjs
  apps/backend/package.json
  apps/backend/prettier.config.js
  apps/web/.prettierignore
  apps/web/.prettierrc
  apps/web/package-lock.json
  apps/web/package.json
  apps/web/prettier.config.js
  docs/monorepo-structure.md
  eslint.config.mjs
  lint-staged.config.mjs
  package-lock.json
  package.json
  packages/eslint-config/nestjs.js
  packages/eslint-config/node.js
  packages/eslint-config/package.json
  packages/linter-config/README.md
  packages/linter-config/lint-staged.js
  packages/linter-config/package.json
  packages/linter-config/scripts/setup.js
  packages/pipeline-runner/eslint.config.js
  packages/pipeline-runner/prettier.config.js
  packages/prettier-config/README.md
  packages/prettier-config/base.js
  packages/prettier-config/package.json
  packages/prettier-config/typescript.js
  packages/prettier-config/web.js
  prettier.config.js
Labels: enhancement

#128 Update README.md in the linter-config
  packages/linter-config/README.md
Labels: documentation

#142 fix(connector): rename 'connector' to 'source' in fields schema references
  packages/connectors/src/Sources/RedditAds/Connector.js
  packages/connectors/src/Sources/TikTokAds/Connector.js
Labels: bug, connector

#145 fix(linter-config): fix lint-staged configurations
  eslint.config.mjs
  lint-staged.config.mjs
  package.json
  packages/eslint-config/nestjs.js
  packages/linter-config/README.md
  packages/linter-config/lint-staged.js
  packages/linter-config/scripts/setup.js
Labels: bug

#169 fix(conntectors): Returned ignoring the launch of the eslinter
  packages/connectors/eslint.config.js
  packages/eslint-config/node.js
Labels: bug

#206 refactor(owox): updare serve
  apps/backend/package.json
  apps/owox/src/commands/serve.ts
Labels: bug
