Repository OWOX/owox-data-marts, pull requests merged in 2025-08, with the labels that each got.

#370 Getting Started Documentation
  docs/getting-started/core-concepts.md
  docs/getting-started/setup-guide/connector-data-mart.md
  docs/getting-started/setup-guide/connector-triggers.md
  docs/getting-started/setup-guide/pattern-data-mart.md
  docs/getting-started/setup-guide/report-triggers.md
  docs/getting-started/setup-guide/sql-data-mart.md
  docs/getting-started/setup-guide/table-data-mart.md
  docs/getting-started/setup-guide/view-data-mart.md
  docs/res/screens/Connector-Based DataMart - 1.png
  docs/res/screens/Connector-Based DataMart - 2.png
  docs/res/screens/Connector-Based DataMart - Connector Config.png
  docs/res/screens/Connector-Based DataMart - Description.png
  docs/res/screens/Connector-Based DataMart - Manual Run.png
  docs/res/screens/Connector-Based DataMart - Output Schema.png
  docs/res/screens/Connector-Based DataMart - Platform Select.png
  docs/res/screens/Connector-Based DataMart - Schema Setup.png
  docs/res/screens/Connector-Trigger-1.png
  docs/res/screens/Manual-run.png
  docs/res/screens/SQL-Based DataMart - 1.png
  docs/res/screens/SQL-Based DataMart - Description.png
  docs/res/screens/SQL-Based DataMart - Output Schema.png
  docs/res/screens/SQL-Based DataMart - Report.png
  docs/res/screens/SQL-Based DataMart - Run Report.png
  docs/res/screens/SQL-Based DataMart - SQL.png
  docs/res/screens/SQL-Based DataMart - Trigger.png
  docs/res/screens/Storage - 1.png
  docs/res/screens/Storage - 2.png
  docs/res/screens/Storage - 3.png
  docs/res/screens/Storage - 4.png
  docs/res/screens/Storage - 5.png
  docs/res/screens/pattern-based-data-mart-1.png
  docs/res/screens/pattern-based-data-mart-2.png
  docs/res/screens/pattern-based-data-mart-3.png
  docs/res/screens/table-data-mart-output-schema.png
  docs/res/screens/table-data-mart-publish.png
  docs/storages/manage-storages.md
  docs/storages/supported-storages/google-bigquery.md
Labels: documentation

#334 feat(web/backend): updated the logic for displaying credentials in Data Storage and Data Destination
  .changeset/improving-credentials-management-security.md
  apps/backend/src/data-marts/data-destination-types/data-destination-credentials.utils.ts
  apps/backend/src/data-marts/data-destination-types/data-destination-providers.ts
  apps/backend/src/data-marts/data-destination-types/factories/data-destination-public-credentials.factory.ts
  apps/backend/src/data-marts/data-storage-types/data-mart-schema.utils.ts
  apps/backend/src/data-marts/data-storage-types/data-storage-providers.ts
  apps/backend/src/data-marts/data-storage-types/factories/data-storage-public-credentials.factory.ts
  apps/backend/src/data-marts/dto/domain/update-data-destination.command.ts
  apps/backend/src/data-marts/dto/domain/update-data-storage.command.ts
  apps/backend/src/data-marts/dto/presentation/data-destination-response-api.dto.ts
  apps/backend/src/data-marts/dto/presentation/data-storage-response-api.dto.ts
  apps/backend/src/data-marts/dto/presentation/update-data-destination-api.dto.ts
  apps/backend/src/data-marts/dto/presentation/update-data-storage-api.dto.ts
  apps/backend/src/data-marts/mappers/data-destination.mapper.ts
  apps/backend/src/data-marts/mappers/data-storage.mapper.ts
  apps/backend/src/data-marts/use-cases/update-data-destination.service.ts
  apps/backend/src/data-marts/use-cases/update-data-storage.service.ts
  apps/web/src/features/data-destination/edit/components/DataDestinationEditForm/DataDestinationForm.tsx
  apps/web/src/features/data-destination/edit/components/DataDestinationEditForm/GoogleSheetsFields.tsx
  apps/web/src/features/data-destination/shared/model/mappers/destination-mapper.interface.ts
  apps/web/src/features/data-destination/shared/model/mappers/google-sheets.mapper.ts
  apps/web/src/features/data-destination/shared/services/types/update-data-destination.request.dto.ts
  apps/web/src/features/data-storage/edit/components/DataStorageEditForm/AwsAthenaFields.tsx
  apps/web/src/features/data-storage/edit/components/DataStorageEditForm/DataStorageForm.tsx
  apps/web/src/features/data-storage/edit/components/DataStorageEditForm/GoogleBigQueryFields.tsx
  apps/web/src/features/data-storage/shared/api/types/request/update-data-storage.request.dto.ts
  apps/web/src/features/data-storage/shared/components/DataStorageDetails/DataStorageDetails.tsx
  apps/web/src/features/data-storage/shared/components/DataStorageInfo/CredentialsSection.tsx
  apps/web/src/features/data-storage/shared/components/DataStorageInfo/DataStorageInfo.tsx
  apps/web/src/features/data-storage/shared/components/DataStorageInfo/index.ts
  apps/web/src/features/data-storage/shared/model/mappers/aws-athena.mapper.ts
  apps/web/src/features/data-storage/shared/model/mappers/google-bigquery.mapper.ts
  apps/web/src/features/data-storage/shared/model/mappers/storage-mapper.interface.ts
  apps/web/src/shared/schemas/google-credentials.schema.ts
  apps/web/src/utils/form-utils.ts
  apps/web/src/utils/google-cloud-utils.ts
Labels: enhancement

#401 fix: comment out unimplemented fields in Facebook Marketing API schemas
  packages/connectors/src/Sources/FacebookMarketing/MarketingAPIReference/FieldsSchema.js
  packages/connectors/src/Sources/FacebookMarketing/MarketingAPIReference/ad-account-fields.js
  packages/connectors/src/Sources/FacebookMarketing/MarketingAPIReference/ad-account-user-fields.js
Labels: connector, schema

#402 docs: clarify Reddit Ads import options and update instructional images
  packages/connectors/src/Sources/RedditAds/GETTING_STARTED.md
  packages/connectors/src/Sources/RedditAds/res/reddit_accountid.png
  packages/connectors/src/Sources/RedditAds/res/reddit_backfill.png
  packages/connectors/src/Sources/RedditAds/res/reddit_credentials.png
  packages/connectors/src/Sources/RedditAds/res/reddit_dataset.png
  packages/connectors/src/Sources/RedditAds/res/reddit_import.png
  packages/connectors/src/Sources/RedditAds/res/reddit_importcurrentday.png
  packages/connectors/src/Sources/RedditAds/res/reddit_pasteid.png
  packages/connectors/src/Sources/RedditAds/res/reddit_reimport.png
  packages/connectors/src/Sources/RedditAds/res/reddit_runbackfill.png
  packages/connectors/src/Sources/RedditAds/res/reddit_tokens.png
Labels: documentation

#416 refactor(LinkedInAds): remove unused fields
  packages/connectors/src/Sources/LinkedInAds/LinkedInAdsAPIReference/adCampaignFields.js
  packages/connectors/src/Sources/LinkedInAds/LinkedInAdsAPIReference/creativesFields.js
Labels: connector

#412 feat(TikTokAds): mark App ID and App Secret as required fields
  packages/connectors/src/Sources/TikTokAds/Source.js
Labels: connector

#421 docs: update Facebook Ads import instructions
  packages/connectors/src/Sources/FacebookMarketing/GETTING_STARTED.md
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_backfill.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_dataset.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_importgbq.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_importsheets.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_newdata.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_reimport.png
  packages/connectors/src/Sources/FacebookMarketing/res/facebook_runbackfill.png
  packages/connectors/src/Sources/FacebookMarketing/res/fb_credentials.png
  packages/connectors/src/Sources/FacebookMarketing/res/fb_fields.png
  packages/connectors/src/Sources/FacebookMarketing/res/fb_pasteid.png
  packages/connectors/src/Sources/FacebookMarketing/res/fb_token.png
Labels: documentation
